displayName=auto-tags
author=i
support=github.com/i/rl-plugins
description=Automatic inventory tags based on item stats
tags=inventory, tags, automatic, dynamic, inventory tags, items, inv
plugins=com.github.i.autotags.AutoTagsPlugin
